# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.vote_radiobtn = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.vote_radiobtn.setGeometry(QtCore.QRect(80, 50, 100, 20))
        self.vote_radiobtn.setObjectName("vote_radiobtn")
        self.exit_radiobtn = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.exit_radiobtn.setGeometry(QtCore.QRect(230, 50, 100, 20))
        self.exit_radiobtn.setObjectName("exit_radiobtn")
        self.vote_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.vote_button.setEnabled(False)
        self.vote_button.setGeometry(QtCore.QRect(130, 190, 113, 32))
        self.vote_button.setObjectName("vote_button")
        self.candidate_comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.candidate_comboBox.setEnabled(False)
        self.candidate_comboBox.setGeometry(QtCore.QRect(190, 140, 104, 26))
        self.candidate_comboBox.setObjectName("candidate_comboBox")
        self.candidate_comboBox.addItem("")
        self.candidate_comboBox.addItem("")
        self.candidate_comboBox.addItem("")
        self.candidate_comboBox.addItem("")
        self.candidates_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.candidates_label.setEnabled(False)
        self.candidates_label.setGeometry(QtCore.QRect(100, 142, 71, 16))
        self.candidates_label.setObjectName("candidates_label")
        self.summary_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.summary_label.setEnabled(False)
        self.summary_label.setGeometry(QtCore.QRect(80, 270, 211, 81))
        self.summary_label.setText("")
        self.summary_label.setWordWrap(True)
        self.summary_label.setObjectName("summary_label")
        self.title_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(150, 230, 60, 16))
        self.title_label.setText("")
        self.title_label.setObjectName("title_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vote Menu"))
        self.vote_radiobtn.setText(_translate("MainWindow", "VOTE"))
        self.exit_radiobtn.setText(_translate("MainWindow", "EXIT"))
        self.vote_button.setText(_translate("MainWindow", "VOTE"))
        self.candidate_comboBox.setItemText(0, _translate("MainWindow", "Allison"))
        self.candidate_comboBox.setItemText(1, _translate("MainWindow", "Cameron"))
        self.candidate_comboBox.setItemText(2, _translate("MainWindow", "Diego"))
        self.candidate_comboBox.setItemText(3, _translate("MainWindow", "Sam"))
        self.candidates_label.setText(_translate("MainWindow", "Candidates:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
